// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AreaLead", b =>
                {
                    b.Property<int>("AreasOfInterestId")
                        .HasColumnType("integer");

                    b.Property<int>("InterestedLeadsId")
                        .HasColumnType("integer");

                    b.HasKey("AreasOfInterestId", "InterestedLeadsId");

                    b.HasIndex("InterestedLeadsId");

                    b.ToTable("AreaLead", (string)null);
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("ActionsCount")
                        .HasColumnType("smallint");

                    b.Property<bool>("AssignToLead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<int>("EventsToListenTo")
                        .HasColumnType("integer");

                    b.Property<string>("FirstActionDelay")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("StopPlanOnInteraction")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TimesSuccess")
                        .HasColumnType("integer");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("integer");

                    b.Property<int>("Triggers")
                        .HasColumnType("integer");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("ActionPlans", (string)null);
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionPlanAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("ActionLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("ActionPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("ActionProperties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<int?>("DataTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("NextActionDelay")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActionPlanId");

                    b.ToTable("Actions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionPlanAssociation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ActionPlanTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomDelay")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<int>("ThisActionPlanStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("TriggeredManually")
                        .HasColumnType("boolean");

                    b.Property<int?>("currentTrackedActionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActionPlanId");

                    b.HasIndex("LeadId");

                    b.ToTable("ActionPlanAssociations", (string)null);
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionTracker", b =>
                {
                    b.Property<int>("ActionPlanAssociationId")
                        .HasColumnType("integer");

                    b.Property<int>("TrackedActionId")
                        .HasColumnType("integer");

                    b.Property<string>("ActionResultId")
                        .HasColumnType("text");

                    b.Property<int>("ActionStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExecutionCompletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HangfireScheduledStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActionPlanAssociationId", "TrackedActionId");

                    b.HasIndex("TrackedActionId");

                    b.ToTable("ActionTrackers", (string)null);
                });

            modelBuilder.Entity("Core.Domain.AgencyAggregate.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminStripeId")
                        .HasColumnType("text");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AzureTenantID")
                        .HasColumnType("text");

                    b.Property<bool>("HasAdminEmailConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("LastCheckoutSessionID")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfBrokersInDatabase")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfBrokersInSubscription")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("SignupDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionLastValidDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Agencies", (string)null);
                });

            modelBuilder.Entity("Core.Domain.AgencyAggregate.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.AgencyAggregate.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<byte>("AssignedBrokersCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DateOfListing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormattedStreetAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LeadsGeneratedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "FormattedStreetAddress");

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AccountActive")
                        .HasColumnType("boolean");

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<int>("AppEventAnalyzerLastId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EmailEventAnalyzerLastTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("LastSeenAppEventId")
                        .HasColumnType("integer");

                    b.Property<int>("LastUnassignedLeadIdAnalyzed")
                        .HasColumnType("integer");

                    b.Property<int>("ListenForActionPlans")
                        .HasColumnType("integer");

                    b.Property<string>("LoginEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("MarkEmailsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TempTimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("isSolo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("Brokers", (string)null);
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.BrokerListingAssignment", b =>
                {
                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ListingId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("assignmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isSeen")
                        .HasColumnType("boolean");

                    b.HasKey("BrokerId", "ListingId");

                    b.HasIndex("ListingId");

                    b.ToTable("BrokerListingAssignments", (string)null);
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.EmailConnection.ConnectedEmail", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<bool>("AssignLeadsAuto")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<byte>("EmailNumber")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("FirstSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GraphSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpenAITokensUsed")
                        .HasColumnType("integer");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubsExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubsRenewalJobId")
                        .HasColumnType("text");

                    b.Property<string>("SyncJobId")
                        .HasColumnType("text");

                    b.Property<bool>("SyncScheduled")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenRefreshJobId")
                        .HasColumnType("text");

                    b.Property<bool>("hasAdminConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("historyId")
                        .HasColumnType("text");

                    b.Property<bool>("isMSFT")
                        .HasColumnType("boolean");

                    b.Property<string>("tenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Email");

                    b.HasIndex("BrokerId");

                    b.HasIndex("GraphSubscriptionId");

                    b.ToTable("ConnectedEmails", (string)null);
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.Templates.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TimesSuccess")
                        .HasColumnType("integer");

                    b.Property<int>("TimesUsed")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("templateLanguage")
                        .HasColumnType("integer");

                    b.Property<string>("templateText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("translatedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("Templates", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Template");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.ToDoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HangfireReminderId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TaskDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("LeadId");

                    b.ToTable("ToDoTasks", (string)null);
                });

            modelBuilder.Entity("Core.Domain.LeadAggregate.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Areas")
                        .HasColumnType("text");

                    b.Property<Guid?>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Budget")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventsForActionPlans")
                        .HasColumnType("integer");

                    b.Property<bool>("HasActionPlanToStop")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastNotifsViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeadFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LeadLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LeadStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ListingId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SourceDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("leadType")
                        .HasColumnType("integer");

                    b.Property<int>("source")
                        .HasColumnType("integer");

                    b.Property<bool>("verifyEmailAddress")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("ListingId");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("Core.Domain.LeadAggregate.LeadEmail", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.HasKey("EmailAddress", "LeadId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadEmails", (string)null);
                });

            modelBuilder.Entity("Core.Domain.LeadAggregate.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<string>("NotesText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("Core.Domain.NotificationAggregate.AppEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteAfterProcessing")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EventTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActionPlanResult")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeadId")
                        .HasColumnType("integer");

                    b.Property<bool>("NotifyBroker")
                        .HasColumnType("boolean");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Props")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReadByBroker")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("LeadId");

                    b.ToTable("AppEvents", (string)null);
                });

            modelBuilder.Entity("Core.Domain.NotificationAggregate.EmailEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BrokerEmail")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConversationId")
                        .HasColumnType("text");

                    b.Property<int?>("LeadId")
                        .HasColumnType("integer");

                    b.Property<bool>("LeadParsedFromEmail")
                        .HasColumnType("boolean");

                    b.Property<string>("LeadProviderEmail")
                        .HasColumnType("text");

                    b.Property<bool>("NeedsAction")
                        .HasColumnType("boolean");

                    b.Property<bool>("RepliedTo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Seen")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeReceived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("TimesReplyNeededReminded")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("LeadId");

                    b.ToTable("EmailEvents", (string)null);
                });

            modelBuilder.Entity("Core.Domain.NotificationAggregate.Notif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<int?>("LeadId")
                        .HasColumnType("integer");

                    b.Property<int>("NotifType")
                        .HasColumnType("integer");

                    b.Property<bool>("isSeen")
                        .HasColumnType("boolean");

                    b.Property<byte>("priority")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("LeadId");

                    b.ToTable("Notifs", (string)null);
                });

            modelBuilder.Entity("Core.Domain.TasksAggregate.RecurrentTaskBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HangfireTaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("RecurrentTasks", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("RecurrentTaskBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LeadTag", b =>
                {
                    b.Property<int>("LeadsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("LeadsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("LeadTag", (string)null);
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.Templates.EmailTemplate", b =>
                {
                    b.HasBaseType("Core.Domain.BrokerAggregate.Templates.Template");

                    b.Property<string>("EmailTemplateSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranslatedEmailTemplateSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("EmailTemplate");
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.Templates.SmsTemplate", b =>
                {
                    b.HasBaseType("Core.Domain.BrokerAggregate.Templates.Template");

                    b.HasDiscriminator().HasValue("SmsTemplate");
                });

            modelBuilder.Entity("Core.Domain.TasksAggregate.BrokerCleanupTask", b =>
                {
                    b.HasBaseType("Core.Domain.TasksAggregate.RecurrentTaskBase");

                    b.HasDiscriminator().HasValue("BrokerCleanupTask");
                });

            modelBuilder.Entity("Core.Domain.TasksAggregate.BrokerNotifAnalyzerTask", b =>
                {
                    b.HasBaseType("Core.Domain.TasksAggregate.RecurrentTaskBase");

                    b.HasDiscriminator().HasValue("BrokerNotifAnalyzerTask");
                });

            modelBuilder.Entity("Core.Domain.TasksAggregate.OutboxDictsTask", b =>
                {
                    b.HasBaseType("Core.Domain.TasksAggregate.RecurrentTaskBase");

                    b.HasDiscriminator().HasValue("OutboxDictsTask");
                });

            modelBuilder.Entity("AreaLead", b =>
                {
                    b.HasOne("Core.Domain.AgencyAggregate.Area", null)
                        .WithMany()
                        .HasForeignKey("AreasOfInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.LeadAggregate.Lead", null)
                        .WithMany()
                        .HasForeignKey("InterestedLeadsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionPlan", b =>
                {
                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "broker")
                        .WithMany("ActionPlans")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("broker");
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionPlanAction", b =>
                {
                    b.HasOne("Core.Domain.ActionPlanAggregate.ActionPlan", "ActionPlan")
                        .WithMany("Actions")
                        .HasForeignKey("ActionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionPlan");
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionPlanAssociation", b =>
                {
                    b.HasOne("Core.Domain.ActionPlanAggregate.ActionPlan", "ActionPlan")
                        .WithMany("ActionPlanAssociations")
                        .HasForeignKey("ActionPlanId");

                    b.HasOne("Core.Domain.LeadAggregate.Lead", "lead")
                        .WithMany("ActionPlanAssociations")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionPlan");

                    b.Navigation("lead");
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionTracker", b =>
                {
                    b.HasOne("Core.Domain.ActionPlanAggregate.ActionPlanAssociation", "ActionPlanAssociation")
                        .WithMany("ActionTrackers")
                        .HasForeignKey("ActionPlanAssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.ActionPlanAggregate.ActionPlanAction", "TrackedAction")
                        .WithMany("ActionTrackers")
                        .HasForeignKey("TrackedActionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ActionPlanAssociation");

                    b.Navigation("TrackedAction");
                });

            modelBuilder.Entity("Core.Domain.AgencyAggregate.Agency", b =>
                {
                    b.OwnsOne("Core.Domain.AgencyAggregate.Agency.Address#Core.Domain.AgencyAggregate.Address", "Address", b1 =>
                        {
                            b1.Property<int>("AgencyId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ProvinceState")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("apt")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AgencyId");

                            b1.ToTable("Agencies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AgencyId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Core.Domain.AgencyAggregate.Area", b =>
                {
                    b.HasOne("Core.Domain.AgencyAggregate.Agency", "Agency")
                        .WithMany("Areas")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Core.Domain.AgencyAggregate.Listing", b =>
                {
                    b.HasOne("Core.Domain.AgencyAggregate.Agency", "Agency")
                        .WithMany("AgencyListings")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Domain.AgencyAggregate.Listing.Address#Core.Domain.AgencyAggregate.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ListingId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ProvinceState")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("apt")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.Broker", b =>
                {
                    b.HasOne("Core.Domain.AgencyAggregate.Agency", "Agency")
                        .WithMany("AgencyBrokers")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.BrokerListingAssignment", b =>
                {
                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "Broker")
                        .WithMany("AssignedListings")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.AgencyAggregate.Listing", "Listing")
                        .WithMany("BrokersAssigned")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.EmailConnection.ConnectedEmail", b =>
                {
                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "Broker")
                        .WithMany("ConnectedEmails")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.Tag", b =>
                {
                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "Broker")
                        .WithMany("BrokerTags")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.Templates.Template", b =>
                {
                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "Broker")
                        .WithMany("Templates")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.ToDoTask", b =>
                {
                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "Broker")
                        .WithMany("Tasks")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.LeadAggregate.Lead", "Lead")
                        .WithMany("ToDoTasks")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Broker");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Core.Domain.LeadAggregate.Lead", b =>
                {
                    b.HasOne("Core.Domain.AgencyAggregate.Agency", "Agency")
                        .WithMany("Leads")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "Broker")
                        .WithMany("Leads")
                        .HasForeignKey("BrokerId");

                    b.HasOne("Core.Domain.AgencyAggregate.Listing", "Listing")
                        .WithMany("LeadsGenerated")
                        .HasForeignKey("ListingId");

                    b.Navigation("Agency");

                    b.Navigation("Broker");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Core.Domain.LeadAggregate.LeadEmail", b =>
                {
                    b.HasOne("Core.Domain.LeadAggregate.Lead", "Lead")
                        .WithMany("LeadEmails")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Core.Domain.LeadAggregate.Note", b =>
                {
                    b.HasOne("Core.Domain.LeadAggregate.Lead", "Lead")
                        .WithOne("Note")
                        .HasForeignKey("Core.Domain.LeadAggregate.Note", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Core.Domain.NotificationAggregate.AppEvent", b =>
                {
                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "Broker")
                        .WithMany("AppEvents")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.LeadAggregate.Lead", "lead")
                        .WithMany("AppEvents")
                        .HasForeignKey("LeadId");

                    b.Navigation("Broker");

                    b.Navigation("lead");
                });

            modelBuilder.Entity("Core.Domain.NotificationAggregate.EmailEvent", b =>
                {
                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "Broker")
                        .WithMany("EmailEvents")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.LeadAggregate.Lead", "lead")
                        .WithMany("EmailEvents")
                        .HasForeignKey("LeadId");

                    b.Navigation("Broker");

                    b.Navigation("lead");
                });

            modelBuilder.Entity("Core.Domain.NotificationAggregate.Notif", b =>
                {
                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "Broker")
                        .WithMany("Notifs")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.LeadAggregate.Lead", "lead")
                        .WithMany("Notifs")
                        .HasForeignKey("LeadId");

                    b.Navigation("Broker");

                    b.Navigation("lead");
                });

            modelBuilder.Entity("Core.Domain.TasksAggregate.RecurrentTaskBase", b =>
                {
                    b.HasOne("Core.Domain.BrokerAggregate.Broker", "Broker")
                        .WithMany("RecurrentTasks")
                        .HasForeignKey("BrokerId");

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("LeadTag", b =>
                {
                    b.HasOne("Core.Domain.LeadAggregate.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.BrokerAggregate.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionPlan", b =>
                {
                    b.Navigation("ActionPlanAssociations");

                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionPlanAction", b =>
                {
                    b.Navigation("ActionTrackers");
                });

            modelBuilder.Entity("Core.Domain.ActionPlanAggregate.ActionPlanAssociation", b =>
                {
                    b.Navigation("ActionTrackers");
                });

            modelBuilder.Entity("Core.Domain.AgencyAggregate.Agency", b =>
                {
                    b.Navigation("AgencyBrokers");

                    b.Navigation("AgencyListings");

                    b.Navigation("Areas");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("Core.Domain.AgencyAggregate.Listing", b =>
                {
                    b.Navigation("BrokersAssigned");

                    b.Navigation("LeadsGenerated");
                });

            modelBuilder.Entity("Core.Domain.BrokerAggregate.Broker", b =>
                {
                    b.Navigation("ActionPlans");

                    b.Navigation("AppEvents");

                    b.Navigation("AssignedListings");

                    b.Navigation("BrokerTags");

                    b.Navigation("ConnectedEmails");

                    b.Navigation("EmailEvents");

                    b.Navigation("Leads");

                    b.Navigation("Notifs");

                    b.Navigation("RecurrentTasks");

                    b.Navigation("Tasks");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("Core.Domain.LeadAggregate.Lead", b =>
                {
                    b.Navigation("ActionPlanAssociations");

                    b.Navigation("AppEvents");

                    b.Navigation("EmailEvents");

                    b.Navigation("LeadEmails");

                    b.Navigation("Note");

                    b.Navigation("Notifs");

                    b.Navigation("ToDoTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
